name: CI Pipeline

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    name: Validar Sintaxe do Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validar Bash script sintaxe
        run: bash -n status-check.sh

  test:
    name: Executar testes
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simular testes rodando
        run: |
          echo "Running tests"
          exit 0

  package:
    name: Empacotar e fazer upload Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Criar report do artifact
        run: |
          mkdir -p output
          echo "Relatório de execução do pipeline" > output/report.txt
          zip -r report.zip output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip

    summary:
      name: Gerar resumo do pipeline
      runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Mostrar informações do ambiente
        run: |
          echo "Sistema operacional do runner: ${{ runner.os }}"
          echo "Branch executada: ${{ github.ref_name }}"

      - name: Mensagem de resumo
        run: |
          echo "Pipeline executado com sucesso."
          echo "::notice::Verifique o artefato gerado no job anterior."

      - name: Incluir link do artefato
        run: echo "::notice::Artefato disponível em: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"