name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_to_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ vars.PROD_DOMAIN }}
    steps:
      - name: Simulate deploy
        run: |
          echo "Deploying to ${{ vars.PROD_DOMAIN }}"