name: Diagnostic Pipeline

permissions:
  issues: write

on: [push]

jobs:
  diagnostic:
    name: Check Required Variables
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Check required environment variables
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Verificando variáveis obrigatórias"

          MISSING_VARS=""
          ISSUE_BODY="## Diagnóstico de Variáveis ausentes\nAs seguintes variáveis obrigatórias não foram encontradas:\n"

          if [ -z "${{ secrets.APP_ENV }}" ]; then
            echo "APP_ENV não está definida."
            MISSING_VARS+="APP_ENV\n"
            ISSUE_BODY+="- APP_ENV\n"
          else
            echo "APP_ENV está definida."
          fi

          if [ -z "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY não está definida."
            MISSING_VARS+="API_KEY\n"
            ISSUE_BODY+="- API_KEY\n"
          else
            echo "API_KEY está definida."
          fi

          if [ -n "$MISSING_VARS" ]; then
            echo -e "Variáveis ausentes detectadas:\n$MISSING_VARS" >> $GITHUB_STEP_SUMMARY
            echo -e "Sugestão:\nAcesse Settings > Secrets and variables > Actions e defina as variáveis ausentes." >> $GITHUB_STEP_SUMMARY

            ISSUE_BODY+="\n**Solução sugerida:**\nAcesse *Settings > Secrets and variables > Actions* e defina as variáveis acima."

            gh issue create --title "Variáveis obrigatórias ausentes" --body "$ISSUE_BODY" --label "bug,diagnostic"

            exit 1
          else
            echo "Todas as variáveis obrigatórias estão definidas." >> $GITHUB_STEP_SUMMARY
          fi